version: '3.7'
services:

  influxdb:
    hostname: influxdb
    image: influxdb:1.7
    restart: unless-stopped
    environment:
    - INFLUXDB_DB=metrics
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin
    - INFLUXDB_USER=docker
    - INFLUXDB_USER_PASSWORD=docker
    - INFLUXDB_UDP_ENABLED=true
    - INFLUXDB_UDP_BIND_ADDRESS=:8089
    - INFLUXDB_UDP_DATABASE=metrics
    volumes:
    - ${PWD-.}/Data/influxdb:/var/lib/influxdb
    networks:
    - backend
    # this can be removed if you want to see influx logs when debugging
    logging:
        driver: "none"

  redis:
    hostname: redis
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "no"]
    volumes:
    - ${PWD-.}/Data/redis:/data
    restart: unless-stopped
    networks:
    - backend
    # this can be removed if you want to see redis logs when debugging
    logging:
        driver: "none"

  nwserver:
    hostname: nwserver
    build:
      context: ./
    volumes:
    - ${PWD-.}/server/:/nwn/home
    - ${PWD-.}/logs:/nwn/run/logs.0
    - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
    restart: unless-stopped
    ports:
    - '5121:5121/udp'
    networks:
    - backend

networks:
    backend: